seed: 0
device: 'cuda:0'
logging:
  path: /home/gear/projects/dhn/runs/
  experiment: default
model:
  layers_config:
   - c2: [21, 5, 2]
     c3: [21, 5, 3]
     c4: [21, 5, 4]
   - c2: [15, 5, 2]
     c3: [15, 5, 3]
     c4: [15, 5, 4]
  out_dim: 10
  agg: [6]
  activation: 
    name: ReLU
    kwargs:
      inplace: False
  dropout: 0.05
training:
  epochs: 100
  batch_size: 32
  early_stopping_patience: 5
  loss:
    name: CrossEntropyLoss
    kwargs:
      reduction: mean
      label_smoothing: 0.0
  optimizer:
    name: AdamW
    kwargs:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 0.00000001
      weight_decay: 0.01
  lr_scheduling: 
    name: ExponentialLR
    kwargs:
      gamma: 0.9
data:
  cross_validation: True  
  dataset: ENZYMES
  root_path: /home/gear/projects/dhn/data
  train_data_path:
  val_data_path:
